export const CLICKFUNNELS_API_TOKEN = process.env.CLICKFUNNELS_API_TOKEN || ""
export const CLICKFUNNELS_SUBDOMAIN = process.env.CLICKFUNNELS_SUBDOMAIN || "myworkspace"
export const CLICKFUNNELS_WORKSPACE_ID = process.env.CLICKFUNNELS_WORKSPACE_ID || ""
